import { createFileRoute } from "@tanstack/react-router";
import { Sparkles, MessagesSquare, Compass, Zap, ShieldCheck, Cpu } from "lucide-react";

export const Route = createFileRoute("/_authenticated/app/gemini")({
  component: GeminiFeatures,
  head: () => ({
    meta: [
      { title: "Gemini AI in Atlas — How it powers the simulation" },
      {
        name: "description",
        content:
          "How Atlas uses Google Gemini for in-character stakeholder conversations, the AI Mentor, real-time context, and graceful fallback.",
      },
    ],
  }),
});

function Feature({
  icon: Icon,
  title,
  children,
}: {
  icon: typeof Sparkles;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border border-border bg-card p-5">
      <div className="flex items-center gap-2 text-sm font-medium">
        <Icon className="h-4 w-4 text-primary" />
        {title}
      </div>
      <div className="mt-2 text-sm leading-relaxed text-muted-foreground">
        {children}
      </div>
    </div>
  );
}

function GeminiFeatures() {
  return (
    <div className="mx-auto max-w-3xl">
      <div className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card/60 px-2.5 py-1 text-[10px] uppercase tracking-[0.16em] text-muted-foreground">
        <Sparkles className="h-3 w-3 text-primary" /> Powered by Google Gemini
      </div>
      <h1 className="mt-3 font-display text-3xl font-semibold tracking-tight">
        Gemini AI in Atlas
      </h1>
      <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
        Atlas is a workplace project-management simulation. Google Gemini powers
        the parts of the experience that must feel alive: the people you email,
        and the mentor that coaches you through decisions.
      </p>

      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        <Feature icon={MessagesSquare} title="AI Stakeholder Conversations">
          Every reply from a stakeholder — sponsor, finance, clinical, vendor,
          care-home lead — is generated by Gemini in that person's tone, given
          the full email thread, project phase, evidence you've submitted, and
          the stakeholder's current sentiment.
        </Feature>
        <Feature icon={Compass} title="AI Mentor (“Ask Atlas”)">
          The floating Ask Atlas panel is a Gemini-backed coach with full
          awareness of your project state: chapter, inbox, tasks, RAID log,
          reputation, health, decisions, and evidence. It coaches — it never
          writes your deliverables for you.
        </Feature>
        <Feature icon={Zap} title="Real-time contextual responses">
          Every Gemini call includes a compact snapshot of the learner's
          workspace at that moment, so replies and coaching reference the exact
          risks, tasks, and people currently on screen — not generic PM theory.
        </Feature>
        <Feature icon={ShieldCheck} title="Graceful fallback">
          If Gemini is unavailable, Atlas falls through a chain — deterministic
          evidence-aware replies, then the Lovable AI gateway, then a static
          reply library. The simulation never breaks; scoring, reputation, and
          tasks all keep working.
        </Feature>
      </div>

      <div className="mt-6 rounded-lg border border-border bg-card p-5">
        <div className="flex items-center gap-2 text-sm font-medium">
          <Cpu className="h-4 w-4 text-primary" /> Architecture at a glance
        </div>
        <ul className="mt-3 space-y-1.5 text-sm text-muted-foreground">
          <li>
            <code className="text-foreground">src/lib/gemini.server.ts</code> —
            single Gemini client (<code>gemini-2.5-flash</code>), text +
            JSON-schema helpers.
          </li>
          <li>
            <code className="text-foreground">
              src/lib/stakeholder-ai.server.ts
            </code>{" "}
            — in-character replies for any role, reusable across features.
          </li>
          <li>
            <code className="text-foreground">src/lib/mentor-ai.server.ts</code>{" "}
            — coaching prompts with a strict “coach, don't complete” rule.
          </li>
          <li>
            <code className="text-foreground">
              src/routes/api/public/gemini-test.ts
            </code>{" "}
            — health check endpoint returning “pong”.
          </li>
        </ul>
        <p className="mt-3 text-xs text-muted-foreground">
          The Atlas UI, database schema, and simulation workflow are unchanged
          by the Gemini integration — it plugs into existing server functions
          and falls back cleanly.
        </p>
      </div>
    </div>
  );
}