/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as AuthenticatedProjectIntroTemplateIdRouteImport } from './routes/_authenticated/project-intro.$templateId'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppStakeholdersRouteImport } from './routes/_authenticated/app.stakeholders'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/app.risk'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app.reviews'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app.progress'
import { Route as AuthenticatedAppMeetingsRouteImport } from './routes/_authenticated/app.meetings'
import { Route as AuthenticatedAppLearningRouteImport } from './routes/_authenticated/app.learning'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppGatesRouteImport } from './routes/_authenticated/app.gates'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppCompletedRouteImport } from './routes/_authenticated/app.completed'
import { Route as AuthenticatedAppCommsRouteImport } from './routes/_authenticated/app.comms'
import { Route as AuthenticatedAppChangesRouteImport } from './routes/_authenticated/app.changes'
import { Route as AuthenticatedAppBudgetRouteImport } from './routes/_authenticated/app.budget'
import { Route as AuthenticatedAdminSignupsRouteImport } from './routes/_authenticated/admin.signups'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectIntroTemplateIdRoute =
  AuthenticatedProjectIntroTemplateIdRouteImport.update({
    id: '/project-intro/$templateId',
    path: '/project-intro/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStakeholdersRoute =
  AuthenticatedAppStakeholdersRouteImport.update({
    id: '/stakeholders',
    path: '/stakeholders',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeetingsRoute =
  AuthenticatedAppMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningRoute =
  AuthenticatedAppLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGatesRoute = AuthenticatedAppGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompletedRoute =
  AuthenticatedAppCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommsRoute = AuthenticatedAppCommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChangesRoute = AuthenticatedAppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBudgetRoute = AuthenticatedAppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminSignupsRoute =
  AuthenticatedAdminSignupsRouteImport.update({
    id: '/admin/signups',
    path: '/admin/signups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/app/budget': typeof AuthenticatedAppBudgetRoute
  '/app/changes': typeof AuthenticatedAppChangesRoute
  '/app/comms': typeof AuthenticatedAppCommsRoute
  '/app/completed': typeof AuthenticatedAppCompletedRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/gates': typeof AuthenticatedAppGatesRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/project-intro/$templateId': typeof AuthenticatedProjectIntroTemplateIdRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/app/budget': typeof AuthenticatedAppBudgetRoute
  '/app/changes': typeof AuthenticatedAppChangesRoute
  '/app/comms': typeof AuthenticatedAppCommsRoute
  '/app/completed': typeof AuthenticatedAppCompletedRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/gates': typeof AuthenticatedAppGatesRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/project-intro/$templateId': typeof AuthenticatedProjectIntroTemplateIdRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/_authenticated/app/budget': typeof AuthenticatedAppBudgetRoute
  '/_authenticated/app/changes': typeof AuthenticatedAppChangesRoute
  '/_authenticated/app/comms': typeof AuthenticatedAppCommsRoute
  '/_authenticated/app/completed': typeof AuthenticatedAppCompletedRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/gates': typeof AuthenticatedAppGatesRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/learning': typeof AuthenticatedAppLearningRoute
  '/_authenticated/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/project-intro/$templateId': typeof AuthenticatedProjectIntroTemplateIdRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/welcome'
    | '/email/unsubscribe'
    | '/admin/signups'
    | '/app/budget'
    | '/app/changes'
    | '/app/comms'
    | '/app/completed'
    | '/app/documents'
    | '/app/gates'
    | '/app/inbox'
    | '/app/learning'
    | '/app/meetings'
    | '/app/progress'
    | '/app/projects'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/tasks'
    | '/project-intro/$templateId'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/app/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/email/unsubscribe'
    | '/admin/signups'
    | '/app/budget'
    | '/app/changes'
    | '/app/comms'
    | '/app/completed'
    | '/app/documents'
    | '/app/gates'
    | '/app/inbox'
    | '/app/learning'
    | '/app/meetings'
    | '/app/progress'
    | '/app/projects'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/tasks'
    | '/project-intro/$templateId'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/app'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/welcome'
    | '/email/unsubscribe'
    | '/_authenticated/admin/signups'
    | '/_authenticated/app/budget'
    | '/_authenticated/app/changes'
    | '/_authenticated/app/comms'
    | '/_authenticated/app/completed'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/gates'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/learning'
    | '/_authenticated/app/meetings'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/risk'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/stakeholders'
    | '/_authenticated/app/tasks'
    | '/_authenticated/project-intro/$templateId'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project-intro/$templateId': {
      id: '/_authenticated/project-intro/$templateId'
      path: '/project-intro/$templateId'
      fullPath: '/project-intro/$templateId'
      preLoaderRoute: typeof AuthenticatedProjectIntroTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stakeholders': {
      id: '/_authenticated/app/stakeholders'
      path: '/stakeholders'
      fullPath: '/app/stakeholders'
      preLoaderRoute: typeof AuthenticatedAppStakeholdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk': {
      id: '/_authenticated/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/meetings': {
      id: '/_authenticated/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AuthenticatedAppMeetingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning': {
      id: '/_authenticated/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AuthenticatedAppLearningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gates': {
      id: '/_authenticated/app/gates'
      path: '/gates'
      fullPath: '/app/gates'
      preLoaderRoute: typeof AuthenticatedAppGatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/completed': {
      id: '/_authenticated/app/completed'
      path: '/completed'
      fullPath: '/app/completed'
      preLoaderRoute: typeof AuthenticatedAppCompletedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comms': {
      id: '/_authenticated/app/comms'
      path: '/comms'
      fullPath: '/app/comms'
      preLoaderRoute: typeof AuthenticatedAppCommsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/changes': {
      id: '/_authenticated/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AuthenticatedAppChangesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/budget': {
      id: '/_authenticated/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AuthenticatedAppBudgetRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/signups': {
      id: '/_authenticated/admin/signups'
      path: '/admin/signups'
      fullPath: '/admin/signups'
      preLoaderRoute: typeof AuthenticatedAdminSignupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBudgetRoute: typeof AuthenticatedAppBudgetRoute
  AuthenticatedAppChangesRoute: typeof AuthenticatedAppChangesRoute
  AuthenticatedAppCommsRoute: typeof AuthenticatedAppCommsRoute
  AuthenticatedAppCompletedRoute: typeof AuthenticatedAppCompletedRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppGatesRoute: typeof AuthenticatedAppGatesRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppLearningRoute: typeof AuthenticatedAppLearningRoute
  AuthenticatedAppMeetingsRoute: typeof AuthenticatedAppMeetingsRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStakeholdersRoute: typeof AuthenticatedAppStakeholdersRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBudgetRoute: AuthenticatedAppBudgetRoute,
  AuthenticatedAppChangesRoute: AuthenticatedAppChangesRoute,
  AuthenticatedAppCommsRoute: AuthenticatedAppCommsRoute,
  AuthenticatedAppCompletedRoute: AuthenticatedAppCompletedRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppGatesRoute: AuthenticatedAppGatesRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppLearningRoute: AuthenticatedAppLearningRoute,
  AuthenticatedAppMeetingsRoute: AuthenticatedAppMeetingsRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStakeholdersRoute: AuthenticatedAppStakeholdersRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedAdminSignupsRoute: typeof AuthenticatedAdminSignupsRoute
  AuthenticatedProjectIntroTemplateIdRoute: typeof AuthenticatedProjectIntroTemplateIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedAdminSignupsRoute: AuthenticatedAdminSignupsRoute,
  AuthenticatedProjectIntroTemplateIdRoute:
    AuthenticatedProjectIntroTemplateIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
